stderr of test 'ID.1078462_run` in directory 'tests/BugsViaSourgeforce` itself:


# 20:48:38 >  
# 20:48:38 >  ( pf -M ID.1078462_run.xq | Mtimeout -timeout 60 Mserver "--config=/var/tmp/_4.4_PREFIX_MONETDB_GNU_32_d_--enable-debug_/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/var/tmp/_4.4_PREFIX_PATHFINDER_GNU_32_d_--enable-debug_/lib/MonetDB:/var/tmp/_4.4_PREFIX_MONETDB_GNU_32_d_--enable-debug_/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_4.4_PREFIX_MONETDB_GNU_32_d_--enable-debug_/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_4.4_PREFIX_MONETDB_GNU_32_d_--enable-debug_/var/MonetDB/log" --set mapi_port=41106 --set sql_port=56072 --set monet_prompt= --dbname=mTests_tests_BugsViaSourgeforce   --dbinit='module(pathfinder,pf_support,ascii_io);' )
# 20:48:38 >  


# 20:48:39 >  
# 20:48:39 >  Done.
# 20:48:39 >  

