stderr of test 'ID.1207029` in directory 'tests/BugsViaSourgeforce` itself:


# 20:31:18 >  
# 20:31:18 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/lib/MonetDB:/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/lib/bin" --set "gdk_dbfarm=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/log" --set mapi_port=39424 --set sql_port=46871 --set xquery_port=51425 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.1207029.milS
# 20:31:18 >  


# 20:31:19 >  
# 20:31:19 >  Done.
# 20:31:19 >  

