stderr of test 'ID.986551` in directory 'monetdb5/tests/BugsViaSourgeforce` itself:


# 11:47:58 >  
# 11:47:58 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/etc/monet.conf" --debug=10 --set "monet_mod_path=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/log" --set mapi_port=45439 --set sql_port=59666 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.986551.milS
# 11:47:58 >  


# 11:47:59 >  
# 11:47:59 >  Done.
# 11:47:59 >  

