stderr of test 'ID.916699` in directory 'monetdb5/tests/BugsViaSourgeforce` itself:


# 17:14:08 >  
# 17:14:08 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_4.3.16_PREFIX_MONET_GNU_32_d__/etc/monet.conf" --debug=10 --set "monet_mod_path=/var/tmp/_4.3.16_PREFIX_MONET_GNU_32_d__/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_4.3.16_PREFIX_MONET_GNU_32_d__/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_4.3.16_PREFIX_MONET_GNU_32_d__/var/MonetDB/log" --set mapi_port=41989 --set sql_port=50213 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.916699.milS
# 17:14:08 >  


# 17:14:09 >  
# 17:14:09 >  Done.
# 17:14:09 >  

