#testing exceptions raised in the kernel

b:= bat.new(:int,:int);
z:= algebra.find(b,0);
io.print("should not come here anymore");
catch MALException:str;
	io.print("catched the exception");
exit MALException;
