stderr of test 'corrupt-attributelist.SF-1483706.remove_doc` in directory 'tests/BugTracker` itself:


# 15:51:06 >  
# 15:51:06 >  Mtimeout -timeout 60 /usr/bin/python corrupt-attributelist.SF-1483706.remove_doc.py corrupt-attributelist.SF-1483706.remove_doc 
# 15:51:06 >  


# 15:51:06 >  
# 15:51:06 >  Done.
# 15:51:06 >  

