stderr of test 'shredding-remap-error.SF-1487156.unpack_doc` in directory 'tests/BugTracker` itself:


# 14:06:08 >  
# 14:06:08 >  Mtimeout -timeout 60 /usr/bin/python shredding-remap-error.SF-1487156.unpack_doc.py shredding-remap-error.SF-1487156.unpack_doc 
# 14:06:08 >  


# 14:06:08 >  
# 14:06:08 >  unzip shredding-remap-error.SF-1487156.unpack_doc.zip
# 14:06:08 >  


# 14:06:08 >  
# 14:06:08 >  Done.
# 14:06:08 >  

