stderr of test 'multiple_servers.SF-1385152` in directory 'tests/BugDay_2005-12-19_0.9.3` itself:


# 19:35:25 >  
# 19:35:25 >  Mtimeout -timeout 180 python multiple_servers.SF-1385152.py multiple_servers.SF-1385152 
# 19:35:25 >  



# 19:35:35 >  
# 19:35:35 >  Done.
# 19:35:35 >  

